# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

lane :lint do
  swiftlint(
    raise_if_swiftlint_error: true,
    strict: true,
    reporter: ENV["CI"] ? "github-actions-logging" : "xcode"
  )
end

lane :ci do
  setup_ci
  build
  # We don't run test for now since the CI only supports macOS 11.6.1 while we are targeting 12.0
end

lane :ci_release do
  setup_ci
  match(type: "development")
  match(type: "developer_id")
  release
end

lane :build do
  build_mac_app(skip_codesigning: true, skip_archive: true, scheme: "Specht2")
end

lane :build_release do
  build_mac_app(export_method: "developer-id", scheme: "Specht2")
end

lane :test do
  scan(xcargs: "CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO")
end

lane :update_version do
  increment_version_number_in_xcodeproj(
    version_number: last_git_tag
  )
  increment_build_number_in_xcodeproj(
    build_number: ENV["GITHUB_RUN_ID"]
  )
end

lane :release do
  update_version
  build_release
  notarize(package: "Specht2.app", asc_provider: "H5443445N6")
  Dir.chdir("..") do
    sh("ditto -c -k --sequesterRsrc --keepParent Specht2.app Specht2.app.zip")
  end
end

lane :init_ci do
  github_action(
    org: "zhuhaow",
    repo: "Specht2",
    match_org: "zhuhaow",
    match_repo: "sign_identity"
  )
end
