# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

lane :lint do
  swiftlint(
    raise_if_swiftlint_error: true,
    strict: true,
    reporter: ENV["CI"] ? "github-actions-logging" : "xcode"
  )
end

lane :ci do
  setup_ci
  build
  test
end

lane :build do
  build_mac_app(skip_codesigning: true, skip_archive: true)
end

lane :test do
  scan
end

lane :release do
  build_mac_app(export_method: "developer-id")
end
