# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

lane :lint do
  swiftlint(
    raise_if_swiftlint_error: true,
    strict: true,
    reporter: ENV["CI"] ? "github-actions-logging" : "xcode"
  )
end

lane :ci do
  setup_ci
  build
  # We don't run test for now since the CI only supports macOS 11.6.1 while we are targeting 12.0
end

lane :ci_release do
  setup_ci
  match(type: "developer_id")
  release
end

lane :build do
  build_mac_app(skip_codesigning: true, skip_archive: true)
end

lane :test do
  scan(xcargs: "CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO")
end

lane :release do
  build_mac_app(export_method: "developer-id")
end

lane :init_ci do
  github_action(
    org: "zhuhaow",
    repo: "Specht2",
    match_org: "zhuhaow",
    match_repo: "sign_identity"
  )
end
